### ISSUE TITLE
Effective Changes to make Battery Saver more useful

### ISSUE THREAD

**Issue by generalvimal** [crdroidandroid/android_device_xiaomi_sweet#4]
Battery Saver does some behind the hood stuff to save battery and I am not aware what it does other than prevent apps from running in background and reducing refresh rate sometimes. But It can also make use of existing settings to become more effective. Please Move the following settings into battery saver:

- Dark theme settings
- Refresh rate settings
- Smart Pixels settings (Settings that saves battery by turning of some pixels on the display thats made by crDdroid)
- Don't keep activities (Developer options)
- Background process limit
- etc.

Also the battery saver needs to be customizable, that is all the above mentioned settings plus more should be toggles plus clickable options. When clicked on them we should be able to configure them and when toggled on they should be triggered when battery saver is turned on.

**Comment by neobuddy89** [comment]
Most of these are as per AOSP design. We do not plan to change in this version of Android.
