### ISSUE TITLE
AOSP Messages app dark mode Issue

### ISSUE THREAD

**Issue by generalvimal** [crdroidandroid/android_device_xiaomi_sweet#5]
- **Issue:**
Unable to read text properly when dark mode is enabled. Might look alright on a laptop or pc screen but the message buble color is lighter than what you see in the image and it makes it real hard to read messages.

- **Possible fixes:**
Make text dark so that it is easy to read in the light coloured bubble

- **Screenshot attached below for reference:**
![image](https://user-images.githubusercontent.com/93727479/181350443-1556be69-a457-4dde-9845-8a99f45f6109.png)

**Comment by neobuddy89** [comment]
FIxed https://github.com/crdroidandroid/android_packages_apps_Messaging/commit/a809f204b5b721d21569b2a75c5cf115c202e1c5
