### ISSUE TITLE
AOSP Messages app settings toggle issue

### ISSUE THREAD

**Issue by generalvimal** [crdroidandroid/android_device_xiaomi_sweet#6]
In the AOSP Messages app, when in dark mode, when a toggle settings is toggled on, the toggle disappears and when it is toggled off it reappears.
Screen recording:

![IMG_20220801_000434_900](https://user-images.githubusercontent.com/93727479/182040502-d45ea1e9-7e0c-452a-b760-063a453aeb74.jpg)

**Comment by neobuddy89** [comment]
This is fixed for next build.
