### ISSUE TITLE
Wi-Fi Hotspot settings improvements

### ISSUE THREAD

**Issue by generalvimal** [crdroidandroid/android_device_xiaomi_sweet#7]
The current Hotspot settings is very simple and minimal and is missing a ton of features. The following can be implemented to make it better:

- No of devices connected
- Data used by each device
- Device connection and Usage history
- Ability to remove a particular connected device
- Hotspot blocklist (Contains list of devices that cannot connect to the hotspot)
- Hotspot Whitelist(Contains list of devices that can connect to the hotspot)
- Hide my hotspot ( Only show hotspot to devices in the whitelist)
- Hotspot channel
- Maximum devices allowed (to connect to hotspot)
- Data Limit (for individual devices connected to the hotspot)

**Comment by gwolf2u** [comment]
This is not device specific and we are using AOSP stuff there
