### ISSUE TITLE
Auto call recording 'Whitelist' feature for AOSP dialler app

### ISSUE THREAD

**Issue by generalvimal** [crdroidandroid/android_device_xiaomi_sweet#8]
Right now the AOSP app records all incoming calls which is both waste of storage space and concern for privacy (since it also records that we don't want it to record). Need a whitelist where phone numbers can be added and calls from the added phone numbers will not be recorded.

**Comment by gwolf2u** [comment]
For now, if you want to record a call, just press the record button while in call
If you want to record all calls, just enable the option in Dialer settings
