### ISSUE TITLE
Camera not working and phone freezing

### ISSUE THREAD

**Issue by 8Ball-Github** [crdroidandroid/android_device_xiaomi_sweet#9]
Since the newest update (02/19/2023) the camera is not working neither in the camera app nor in any other app.

Also during the night my phone freezes and when i wake up i have to force restart it.
It also froze a few times during usage.

On the update prior (Feruary update) everything worked fine.

Redmi Note 10 Pro

**Comment by gwolf2u** [comment]
use issue_tracker repo
